FROM maven:3.8.3-openjdk-11-slim AS build

RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/GreenLive-Agriculture/greenlive_dashboard.git /app && git checkout master && git pull

WORKDIR /app

RUN mvn clean install

FROM openjdk:11-jre-slim

COPY --from=build /app/target/*.jar /app/api_greenlive.jar

WORKDIR /app

CMD ["java", "-jar", "api_greenlive.jar"]