FROM maven:3.8.3-openjdk-17-slim AS build

RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/GreenLive-Agriculture/greenlive_dashboard.git -b master /app

WORKDIR /app/greenlive_api

RUN mvn clean install

FROM openjdk:17-jdk-slim

COPY --from=build /app/target/*.jar /app/api_greenlive.jar

WORKDIR /app

CMD ["java", "-jar", "api_greenlive.jar"]